name: dev-cd-wf
on:
  push:
    branches:
      - develop
jobs:
  dev-dep-job:
    environment: "development"
    runs-on: ubuntu-latest
    steps:
      - name: Dev Deployment Job
        run: echo "your app is going to deploy on render"
      - name: send message to render
      # call back url 
        run: curl -X POST ${{secrets.RENDER_DEP_HOOK}}