name: ci-wf
on:
  pull_request:
    branches:
      - develop
      - main
    types:
      - opened
      - synchronize
jobs:
  linting-job:
    runs-on: ubuntu-latest
    steps:
      - name: Linting Job
        run: echo "Starting Linting of html and css files"
      - name: Clone repo on the Runner
        uses: actions/checkout@v6
      - name: Install Dev Dependencies
        run: npm install
      - name: Lint Html Files
        run: npx htmlhint "**/*.html"
      - name: Lint Css Files
        run: npx stylelint "**/*.css"
  
  build-job:
    runs-on: ubuntu-latest
    needs: "linting-job"
    steps:
      - name: Build Job 
        run: echo "build job goint to start"
      - name: Clone repo
        uses: actions/checkout@v6
      - name: Install Dependencies
        run: npm install
      - name: Build website 
        run:  npx parcel build "./src/index.html" --dist-dir "./dist" --public-url "./" --no-cache
     
  image-build-job:
    runs-on: ubuntu-latest
    needs: "build-job"
    steps:
      - name: Clone repo to build image
        uses: actions/checkout@v6   
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build image
        run: docker image build -t ${{ secrets.DOCKERHUB_USERNAME }}/uni-notice-board:lastest .
      - name: list images on runner 
        run : docker image ls
      - name: create container on runner
        run: docker container run -d -p 2222:80 ${{ secrets.DOCKERHUB_USERNAME }}/uni-notice-board:lastest
      - name: List Running Containers
        run: docker container ls
      - name: push docker image on Dh
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/uni-notice-board:lastest
